/** 3D Prints catalog — generated by scripts/extract-cooler-images.py */
window.PRINTS_DATA = {
  categories: [
  {
    "id": "coolers",
    "title": "Coolers",
    "desc": "Branded can coolers and coozies from the workroom.",
    "href": "/prints/coolers/",
    "cover": "/assets/prints/coolers/baja-blast-cooler.png"
  }
],
  items: [],
  perPage: 60,
  buyHref: "/shop/coming-soon/",
};

function humanizeCoolerName(filename) {
  return filename.replace(/\.3mf$/i, "").replace(/[_-]+/g, " ");
}

function getPrintItems({ category = null } = {}) {
  const items = window.PRINTS_DATA.items || [];
  if (!category) return items.slice();
  return items.filter((item) => item.category === category);
}

function getPrintPageItems({ category = null, page = 1, perPage = null } = {}) {
  const all = getPrintItems({ category });
  const size = perPage || window.PRINTS_DATA.perPage || 60;
  const totalPages = Math.max(1, Math.ceil(all.length / size));
  const safePage = Math.min(Math.max(1, page), totalPages);
  const start = (safePage - 1) * size;
  return {
    items: all.slice(start, start + size),
    page: safePage,
    totalPages,
    totalItems: all.length,
    perPage: size,
  };
}

function renderPrintsBackLink(href, label) {
  return `<p class="print-back"><a href="${href}">&larr; ${label}</a></p>`;
}

function renderPrintPagination({ basePath, page, totalPages }) {
  if (totalPages <= 1) return "";
  const pages = [];
  for (let i = 1; i <= totalPages; i += 1) {
    const href = i === 1 ? basePath : `${basePath.replace(/\/$/, "")}/page-${i}/`;
    pages.push(
      `<a class="print-pagination-link${i === page ? " active" : ""}" href="${href}">Page ${i}</a>`
    );
  }
  return `<nav class="print-pagination" aria-label="Print catalog pages">${pages.join("")}</nav>`;
}

function renderPrintTile(item) {
  return `<button type="button" class="print-tile" data-print-id="${item.id}" aria-label="View ${item.name}">
    <img src="${item.image}" alt="" class="print-tile-image" loading="lazy" width="400" height="400" />
    <span class="print-tile-name">${item.name}</span>
  </button>`;
}

function renderPrintGrid({ category = null, page = 1, perPage = null, basePath = "/prints/all/" } = {}) {
  const result = getPrintPageItems({ category, page, perPage });
  const categoryLabel = category
    ? (window.PRINTS_DATA.categories || []).find((c) => c.id === category)?.title || "Prints"
    : "All files";
  return `${renderPrintsBackLink("/prints/", "All print categories")}
    <header class="page-header">
      <p class="pillar-eyebrow">3D prints</p>
      <h1>${categoryLabel}</h1>
      <p>${result.totalItems} design${result.totalItems === 1 ? "" : "s"} — click a tile for a larger preview, then buy when our store opens.</p>
    </header>
    <div class="print-grid" role="list">
      ${result.items.map(renderPrintTile).join("")}
    </div>
    ${renderPrintPagination({ basePath, page: result.page, totalPages: result.totalPages })}`;
}

function renderPrintsHub() {
  const categories = window.PRINTS_DATA.categories || [];
  const total = (window.PRINTS_DATA.items || []).length;
  const tiles = categories
    .map(
      (cat) => `<a class="prints-category-card" href="${cat.href}">
        <img src="${cat.cover}" alt="" class="prints-category-cover" loading="lazy" width="480" height="360" />
        <div class="prints-category-copy">
          <h2>${cat.title}</h2>
          <p>${cat.desc}</p>
        </div>
      </a>`
    )
    .join("");

  return `<header class="page-header">
      <p class="pillar-eyebrow">From the workroom</p>
      <h1>3D print files</h1>
      <p>Browse our sellable prints — coolers, coozies, and more as we add categories. Click any design for a closer look.</p>
    </header>
    <section class="prints-category-grid">
      ${tiles}
      <a class="prints-category-card" href="/prints/all/">
        <div class="prints-category-cover prints-category-cover-all" aria-hidden="true">
          <span>All</span>
        </div>
        <div class="prints-category-copy">
          <h2>All files</h2>
          <p>Every print in one catalog — ${total} design${total === 1 ? "" : "s"} right now.</p>
        </div>
      </a>
    </section>`;
}

function ensurePrintLightbox() {
  let overlay = document.getElementById("print-lightbox");
  if (overlay) return overlay;

  overlay = document.createElement("div");
  overlay.id = "print-lightbox";
  overlay.className = "print-lightbox";
  overlay.hidden = true;
  overlay.innerHTML = `<div class="print-lightbox-dialog" role="dialog" aria-modal="true" aria-labelledby="print-lightbox-title">
      <button type="button" class="print-lightbox-close" aria-label="Close preview">&times;</button>
      <img class="print-lightbox-image" alt="" />
      <div class="print-lightbox-actions">
        <h2 id="print-lightbox-title" class="print-lightbox-title"></h2>
        <div class="print-lightbox-buttons">
          <a class="btn btn-primary print-lightbox-buy" href="${window.PRINTS_DATA.buyHref || "/shop/coming-soon/"}">Buy</a>
          <button type="button" class="btn btn-ghost print-lightbox-dismiss">Close</button>
        </div>
      </div>
    </div>`;
  document.body.appendChild(overlay);
  return overlay;
}

function closePrintLightbox() {
  const overlay = document.getElementById("print-lightbox");
  if (!overlay) return;
  overlay.hidden = true;
  document.body.classList.remove("print-lightbox-open");
}

function openPrintLightbox(item) {
  const overlay = ensurePrintLightbox();
  const img = overlay.querySelector(".print-lightbox-image");
  const title = overlay.querySelector(".print-lightbox-title");
  const buy = overlay.querySelector(".print-lightbox-buy");
  if (!img || !title || !buy) return;

  img.src = item.image;
  img.alt = item.name;
  title.textContent = item.name;
  buy.href = window.PRINTS_DATA.buyHref || "/shop/coming-soon/";
  overlay.hidden = false;
  document.body.classList.add("print-lightbox-open");
  overlay.querySelector(".print-lightbox-close")?.focus();
}

function initPrintLightbox() {
  ensurePrintLightbox();
  const overlay = document.getElementById("print-lightbox");
  if (!overlay) return;

  const byId = Object.fromEntries((window.PRINTS_DATA.items || []).map((item) => [item.id, item]));

  document.querySelectorAll(".print-tile[data-print-id]").forEach((tile) => {
    tile.addEventListener("click", () => {
      const item = byId[tile.getAttribute("data-print-id") || ""];
      if (item) openPrintLightbox(item);
    });
  });

  overlay.addEventListener("click", (event) => {
    if (event.target === overlay) closePrintLightbox();
  });
  overlay.querySelector(".print-lightbox-close")?.addEventListener("click", closePrintLightbox);
  overlay.querySelector(".print-lightbox-dismiss")?.addEventListener("click", closePrintLightbox);

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && !overlay.hidden) closePrintLightbox();
  });
}

function initPrintsPage({ title, description, activePath, content, adSlots = true }) {
  initPage({ title, description, activePath, content, adSlots });
  document.querySelectorAll(".page-main .reveal, .print-grid, .print-pagination").forEach((node) => {
    node.classList.add("is-visible");
  });
  initPrintLightbox();
}
