#!/usr/bin/env python3
"""Extract Metadata/plate_1.png from cooler .3mf files and regenerate prints.js catalog."""

from __future__ import annotations

import json
import re
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = Path(r"G:\Laughing Dragons\3d Models\Ready To Sell Coolers")
OUT_DIR = ROOT / "assets" / "prints" / "coolers"
PRINTS_JS = ROOT / "assets" / "js" / "prints.js"

THUMB = "Metadata/plate_1.png"


def slugify(name: str) -> str:
    base = Path(name).stem
    slug = base.lower().replace(" ", "-")
    slug = re.sub(r"[^a-z0-9-]+", "-", slug)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return slug


def humanize(name: str) -> str:
    base = Path(name).stem
    spaced = re.sub(r"([a-z])([A-Z])", r"\1 \2", base)
    spaced = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", spaced)
    spaced = re.sub(r"(\d+)([A-Za-z])", r"\1 \2", spaced)
    spaced = re.sub(r"([A-Za-z])(\d+)", r"\1 \2", spaced)
    spaced = spaced.replace("_", " ")
    words = spaced.split()
    out: list[str] = []
    for word in words:
        if word.isupper() and len(word) <= 4:
            out.append(word)
        elif word.isdigit():
            out.append(word)
        else:
            out.append(word.capitalize())
    return " ".join(out)


def extract_images() -> tuple[list[dict], list[str]]:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    items: list[dict] = []
    missing: list[str] = []

    for path in sorted(SOURCE.glob("*.3mf")):
        slug = slugify(path.name)
        out_path = OUT_DIR / f"{slug}.png"
        try:
            with zipfile.ZipFile(path) as zf:
                if THUMB not in zf.namelist():
                    missing.append(path.name)
                    continue
                out_path.write_bytes(zf.read(THUMB))
        except (OSError, zipfile.BadZipFile) as exc:
            missing.append(f"{path.name} ({exc})")
            continue

        items.append(
            {
                "id": slug,
                "name": humanize(path.name),
                "category": "coolers",
                "image": f"/assets/prints/coolers/{slug}.png",
            }
        )

    return items, missing


def write_prints_js(items: list[dict]) -> None:
    cover = next(
        (
            i["image"]
            for pref in ["bajablastcooler", "375bajablastcooler", "cocacolacooler"]
            for i in items
            if i["id"] == pref
        ),
        items[0]["image"] if items else "/assets/prints/coolers/baja-blast-cooler.png",
    )

    data = {
        "categories": [
            {
                "id": "coolers",
                "title": "Coolers",
                "desc": "Branded can coolers and coozies from the workroom.",
                "href": "/prints/coolers/",
                "cover": cover,
            }
        ],
        "items": items,
        "perPage": 60,
        "buyHref": "/shop/coming-soon/",
    }

    items_json = json.dumps(items, indent=2)
    categories_json = json.dumps(data["categories"], indent=2)

    content = f'''/** 3D Prints catalog — generated by scripts/extract-cooler-images.py */
window.PRINTS_DATA = {{
  categories: {categories_json},
  items: {items_json},
  perPage: 60,
  buyHref: "/shop/coming-soon/",
}};

function humanizeCoolerName(filename) {{
  return filename.replace(/\\.3mf$/i, "").replace(/[_-]+/g, " ");
}}

function getPrintItems({{ category = null }} = {{}}) {{
  const items = window.PRINTS_DATA.items || [];
  if (!category) return items.slice();
  return items.filter((item) => item.category === category);
}}

function getPrintPageItems({{ category = null, page = 1, perPage = null }} = {{}}) {{
  const all = getPrintItems({{ category }});
  const size = perPage || window.PRINTS_DATA.perPage || 60;
  const totalPages = Math.max(1, Math.ceil(all.length / size));
  const safePage = Math.min(Math.max(1, page), totalPages);
  const start = (safePage - 1) * size;
  return {{
    items: all.slice(start, start + size),
    page: safePage,
    totalPages,
    totalItems: all.length,
    perPage: size,
  }};
}}

function renderPrintsBackLink(href, label) {{
  return `<p class="print-back reveal"><a href="${{href}}">&larr; ${{label}}</a></p>`;
}}

function renderPrintPagination({{ basePath, page, totalPages }}) {{
  if (totalPages <= 1) return "";
  const pages = [];
  for (let i = 1; i <= totalPages; i += 1) {{
    const href = i === 1 ? basePath : `${{basePath.replace(/\\/$/, "")}}/page-${{i}}/`;
    pages.push(
      `<a class="print-pagination-link${{i === page ? " active" : ""}}" href="${{href}}">Page ${{i}}</a>`
    );
  }}
  return `<nav class="print-pagination" aria-label="Print catalog pages">${{pages.join("")}}</nav>`;
}}

function renderPrintTile(item) {{
  return `<button type="button" class="print-tile" data-print-id="${{item.id}}" aria-label="View ${{item.name}}">
    <img src="${{item.image}}" alt="" class="print-tile-image" loading="lazy" width="400" height="400" />
    <span class="print-tile-name">${{item.name}}</span>
  </button>`;
}}

function renderPrintGrid({{ category = null, page = 1, perPage = null, basePath = "/prints/all/" }} = {{}}) {{
  const result = getPrintPageItems({{ category, page, perPage }});
  const categoryLabel = category
    ? (window.PRINTS_DATA.categories || []).find((c) => c.id === category)?.title || "Prints"
    : "All files";
  return `${{renderPrintsBackLink("/prints/", "All print categories")}}
    <header class="page-header reveal">
      <p class="pillar-eyebrow">3D prints</p>
      <h1>${{categoryLabel}}</h1>
      <p>${{result.totalItems}} design${{result.totalItems === 1 ? "" : "s"}} — click a tile for a larger preview, then buy when our store opens.</p>
    </header>
    <div class="print-grid" role="list">
      ${{result.items.map(renderPrintTile).join("")}}
    </div>
    ${{renderPrintPagination({{ basePath, page: result.page, totalPages: result.totalPages }})}}`;
}}

function renderPrintsHub() {{
  const categories = window.PRINTS_DATA.categories || [];
  const total = (window.PRINTS_DATA.items || []).length;
  const tiles = categories
    .map(
      (cat) => `<a class="prints-category-card reveal" href="${{cat.href}}">
        <img src="${{cat.cover}}" alt="" class="prints-category-cover" loading="lazy" width="480" height="360" />
        <div class="prints-category-copy">
          <h2>${{cat.title}}</h2>
          <p>${{cat.desc}}</p>
        </div>
      </a>`
    )
    .join("");

  return `<header class="page-header reveal">
      <p class="pillar-eyebrow">From the workroom</p>
      <h1>3D print files</h1>
      <p>Browse our sellable prints — coolers, coozies, and more as we add categories. Click any design for a closer look.</p>
    </header>
    <section class="prints-category-grid reveal">
      ${{tiles}}
      <a class="prints-category-card" href="/prints/all/">
        <div class="prints-category-cover prints-category-cover-all" aria-hidden="true">
          <span>All</span>
        </div>
        <div class="prints-category-copy">
          <h2>All files</h2>
          <p>Every print in one catalog — ${{total}} design${{total === 1 ? "" : "s"}} right now.</p>
        </div>
      </a>
    </section>`;
}}

function ensurePrintLightbox() {{
  let overlay = document.getElementById("print-lightbox");
  if (overlay) return overlay;

  overlay = document.createElement("div");
  overlay.id = "print-lightbox";
  overlay.className = "print-lightbox";
  overlay.hidden = true;
  overlay.innerHTML = `<div class="print-lightbox-dialog" role="dialog" aria-modal="true" aria-labelledby="print-lightbox-title">
      <button type="button" class="print-lightbox-close" aria-label="Close preview">&times;</button>
      <img class="print-lightbox-image" alt="" />
      <div class="print-lightbox-actions">
        <h2 id="print-lightbox-title" class="print-lightbox-title"></h2>
        <div class="print-lightbox-buttons">
          <a class="btn btn-primary print-lightbox-buy" href="${{window.PRINTS_DATA.buyHref || "/shop/coming-soon/"}}">Buy</a>
          <button type="button" class="btn btn-ghost print-lightbox-dismiss">Close</button>
        </div>
      </div>
    </div>`;
  document.body.appendChild(overlay);
  return overlay;
}}

function closePrintLightbox() {{
  const overlay = document.getElementById("print-lightbox");
  if (!overlay) return;
  overlay.hidden = true;
  document.body.classList.remove("print-lightbox-open");
}}

function openPrintLightbox(item) {{
  const overlay = ensurePrintLightbox();
  const img = overlay.querySelector(".print-lightbox-image");
  const title = overlay.querySelector(".print-lightbox-title");
  const buy = overlay.querySelector(".print-lightbox-buy");
  if (!img || !title || !buy) return;

  img.src = item.image;
  img.alt = item.name;
  title.textContent = item.name;
  buy.href = window.PRINTS_DATA.buyHref || "/shop/coming-soon/";
  overlay.hidden = false;
  document.body.classList.add("print-lightbox-open");
  overlay.querySelector(".print-lightbox-close")?.focus();
}}

function initPrintLightbox() {{
  ensurePrintLightbox();
  const overlay = document.getElementById("print-lightbox");
  if (!overlay) return;

  const byId = Object.fromEntries((window.PRINTS_DATA.items || []).map((item) => [item.id, item]));

  document.querySelectorAll(".print-tile[data-print-id]").forEach((tile) => {{
    tile.addEventListener("click", () => {{
      const item = byId[tile.getAttribute("data-print-id") || ""];
      if (item) openPrintLightbox(item);
    }});
  }});

  overlay.addEventListener("click", (event) => {{
    if (event.target === overlay) closePrintLightbox();
  }});
  overlay.querySelector(".print-lightbox-close")?.addEventListener("click", closePrintLightbox);
  overlay.querySelector(".print-lightbox-dismiss")?.addEventListener("click", closePrintLightbox);

  document.addEventListener("keydown", (event) => {{
    if (event.key === "Escape" && !overlay.hidden) closePrintLightbox();
  }});
}}

function initPrintsPage({{ title, description, activePath, content, adSlots = true }}) {{
  initPage({{ title, description, activePath, content, adSlots }});
  document.querySelectorAll(".print-grid, .print-pagination").forEach((node) => {{
    node.classList.add("is-visible");
  }});
  initPrintLightbox();
}}
'''
    PRINTS_JS.write_text(content, encoding="utf-8")


def main() -> int:
    if not SOURCE.is_dir():
        print(f"Source folder not found: {SOURCE}")
        return 1

    items, missing = extract_images()
    write_prints_js(items)

    print(f"Extracted {len(items)} images to {OUT_DIR}")
    if missing:
        print(f"Missing plate_1.png in {len(missing)} file(s):")
        for name in missing:
            print(f"  - {name}")
    print(f"Wrote {PRINTS_JS}")
    return 0 if not missing else 2


if __name__ == "__main__":
    raise SystemExit(main())
